# -*- coding: utf-8 -*-
"""cross_impact

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OI5Gslqutk5YZOqDMPQClNH_cIPKU9Q
"""



import pandas as pd
from sklearn.linear_model import LassoCV
from sklearn.model_selection import train_test_split

def cross_impact_model(df):
    """
    Perform cross-impact analysis using LASSO regression.

    Args:
        df (pd.DataFrame): DataFrame with OFI and return data.

    Returns:
        dict: Coefficients from the model.
    """
    X = df[['ofi1', 'ofi2', 'ofi3']]  # Replace with actual OFI features
    y = df['returns']
    model = LassoCV(cv=5).fit(X, y)
    return dict(zip(X.columns, model.coef_))

if __name__ == "__main__":
    data_path = "data/ofi_data.csv"
    df = pd.read_csv(data_path)
    model_coefficients = cross_impact_model(df)
    print("Model coefficients:", model_coefficients)